#!/usr/bin/env python3
"""The wiki's QR code with the cabinet in the middle (#314, How to > Wiki).

WHY IT IS MADE HERE AND NOT ON THE CONSOLE. The address never changes, so the
code is made once, by segno (a tested encoder), at error correction H: a
third of the code can be lost and it still reads, which is what lets the
cabinet cover its middle. The console's own encoder (qr.cpp) stays at level M
for the codes it makes at run time (pairing, Tailscale, the diagnostic
report) and is not touched. MMagTech, 2026-10-10.

What it writes: frontend/src/wikiqr.h, the modules as rows of text, and the
patch in the middle (in modules) that the console fills with white and the
cabinet. With --preview PATH, a picture of the code as the console draws it,
and both OpenCV readers must decode it at TV-photo sizes or this fails.

    python3 tools/make-wiki-qr.py --preview /tmp/wiki-qr.png
"""

import argparse
import os
import sys

import segno

URL = "https://mmagtech.github.io/cabinetos/wiki/"
# The patch, in modules, centred: white, then a purple tile (the startup
# screen's purple, so the cream cabinet stands out, MMagTech 2026-10-10), then
# the cabinet. 14% of the code: MEASURED as the largest that reads exactly as
# well as a plain level-H code (9x11, 11x13 and 13x15 all did; 15x17 lost a
# reader at two sizes; 17x19 read at none). Clear of the finder, timing and
# alignment patterns.
PATCH_W, PATCH_H = 13, 15
# The tile and the cabinet inside the patch, in modules. The console draws
# them from these (settings.cpp), so the preview is what the TV shows.
WHITE_RADIUS, TILE_INSET, TILE_RADIUS = 1.2, 0.5, 1.4
CABINET_TOP, CABINET_SHORT = 1.2, 2.4      # from the patch's top; patch height minus this
PURPLE = (0x3A, 0x22, 0x68)                # ui::palette::kBackdropTop
QUIET = 4

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "frontend", "src", "wikiqr.h")


def make():
    q = segno.make(URL, error="h", micro=False, boost_error=False)
    rows = [[1 if m else 0 for m in row] for row in q.matrix]
    n = len(rows)
    px = (n - PATCH_W) // 2
    py = (n - PATCH_H) // 2
    return q, rows, n, px, py


def write_header(q, rows, n, px, py):
    lines = ["".join("#" if m else "." for m in r) for r in rows]
    body = ",\n".join('    "%s"' % l for l in lines)
    text = f"""// GENERATED by tools/make-wiki-qr.py. Do not edit; run the tool.
//
// The wiki's address as a QR code, version {q.version}, error correction H, so
// the cabinet can cover the patch in its middle and it still reads. Made once
// because the address never changes; qr.cpp is not used for it.

#pragma once

namespace wikiqr {{

constexpr const char* kUrl = "{URL}";
constexpr int kSize = {n};
// The patch the console fills with white, a purple tile and the cabinet, in
// modules, and how those sit in it.
constexpr int kPatchX = {px}, kPatchY = {py}, kPatchW = {PATCH_W}, kPatchH = {PATCH_H};
constexpr float kWhiteRadius = {WHITE_RADIUS}f, kTileInset = {TILE_INSET}f, kTileRadius = {TILE_RADIUS}f;
constexpr float kCabinetTop = {CABINET_TOP}f, kCabinetShort = {CABINET_SHORT}f;
// One string per row, '#' dark.
constexpr const char* kRows[kSize] = {{
{body}
}};

}}  // namespace wikiqr
"""
    with open(OUT, "w") as f:
        f.write(text)


def cabinet(draw, x, y, h):
    """The cabinet as setup.cpp's drawCabinet draws it, top-left at x,y,
    `h` tall (its 1024 space spans x 248..775, y 130..850)."""
    s = h / 720.0
    ox, oy = x - 248 * s, y - 130 * s

    def R(rx, ry, w, hh, rad, col):
        draw.rounded_rectangle([ox + rx * s, oy + ry * s, ox + (rx + w) * s, oy + (ry + hh) * s],
                               radius=rad * s, fill=col)

    def dot(cx, cy, rad, col):
        R(cx - rad, cy - rad, rad * 2, rad * 2, rad, col)

    R(268, 130, 488, 670, 42, (0xF2, 0xEE, 0xE8))
    R(318, 176, 390, 84, 16, (0xFF, 0xB0, 0x9C))   # the marquee's ramp, at its middle
    R(316, 292, 394, 284, 18, (0xF5, 0x9C, 0x62))  # the screen's ramp, at its middle
    R(248, 600, 527, 112, 20, (0xD7, 0xD1, 0xC8))
    dot(348, 656, 30, (0x3A, 0x34, 0x44))
    dot(500, 656, 25, (0xEC, 0x40, 0x5C))
    dot(583, 656, 24, (0xFF, 0xC4, 0x57))
    R(668, 646, 48, 20, 10, (0xFF, 0xF0, 0xE2))
    R(303, 795, 419, 55, 14, (0xD7, 0xD1, 0xC8))


def render(rows, n, px, py, module):
    from PIL import Image, ImageDraw
    side = (n + 2 * QUIET) * module
    img = Image.new("RGB", (side, side), "white")
    d = ImageDraw.Draw(img)
    for y, r in enumerate(rows):
        for x, m in enumerate(r):
            if m:
                X, Y = (x + QUIET) * module, (y + QUIET) * module
                d.rectangle([X, Y, X + module - 1, Y + module - 1], fill="black")
    # The patch: white, the purple tile, then the cabinet.
    X, Y = (px + QUIET) * module, (py + QUIET) * module
    d.rounded_rectangle([X, Y, X + PATCH_W * module, Y + PATCH_H * module],
                        radius=module * WHITE_RADIUS, fill="white")
    t = TILE_INSET * module
    d.rounded_rectangle([X + t, Y + t, X + PATCH_W * module - t, Y + PATCH_H * module - t],
                        radius=module * TILE_RADIUS, fill=PURPLE)
    ch = (PATCH_H - CABINET_SHORT) * module
    cw = ch * 527.0 / 720.0
    cabinet(d, X + (PATCH_W * module - cw) / 2, Y + CABINET_TOP * module, ch)
    return img


def decodes(img):
    import cv2
    import numpy as np
    a = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2GRAY)
    out = []
    for name, det in (("opencv", cv2.QRCodeDetector()), ("aruco", cv2.QRCodeDetectorAruco())):
        text, _, _ = det.detectAndDecode(a)
        out.append((name, text))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview")
    args = ap.parse_args()
    q, rows, n, px, py = make()
    write_header(q, rows, n, px, py)
    print(f"version {q.version}, {n}x{n}, level {q.error}, patch {PATCH_W}x{PATCH_H} at {px},{py} "
          f"({100.0 * PATCH_W * PATCH_H / (n * n):.1f}% of the modules)")
    if not args.preview:
        return 0
    from PIL import Image, ImageFilter
    big = render(rows, n, px, py, 20)
    big.save(args.preview)
    # The console's size and photo-of-a-TV sizes, smaller and softened. A
    # phone runs one reader, so a size passes when either reads it. Measured
    # 2026-10-10: a PLAIN level-H code of the same version fails the same
    # sizes as this one (it is denser than level M's version 3), so the
    # cabinet costs nothing over level H itself; under 140 px both fail.
    failed = 0
    for width, blur in ((900, 0), (300, 0), (220, 0.5), (160, 0.6), (140, 0.7)):
        im = big.resize((width, width), Image.LANCZOS)
        if blur:
            im = im.filter(ImageFilter.GaussianBlur(blur))
        got = decodes(im)
        ok = any(text == URL for _, text in got)
        failed += not ok
        print(f"  {'ok  ' if ok else 'FAIL'} at {width}px{' blurred' if blur else ''}: "
              + ", ".join(f"{n} {'read' if t == URL else 'no'}" for n, t in got))
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
